services:
  # Base de données PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: cesizen_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE:-flow_db}
      POSTGRES_USER: ${DB_USERNAME:-flow_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret_password}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - cesizen_net

  # Base de données MongoDB
  mongo:
    image: mongo:7.0
    container_name: cesizen_mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - cesizen_net

# Backend API Laravel
  backend:
    build:
      context: ./flow-backend
      dockerfile: Dockerfile
    container_name: cesizen_backend
    restart: always
    command: php artisan serve --host=0.0.0.0 --port=8000
    ports:
      - "8000:8000"
    env_file:
      - ./flow-backend/.env
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=flow_db
      - DB_USERNAME=flow_user
      - DB_PASSWORD=secret_password
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=flow_db
      - MONGODB_URI=mongodb://mongo:27017/flow_db
    depends_on:
      - db
      - mongo
    networks:
      - cesizen_net

# Frontend Web Next.js
  frontend:
      build:
        context: ./flow-web
        dockerfile: Dockerfile
      container_name: cesizen_frontend
      restart: always
      ports:
        - "3000:3000"
      environment:
        - AUTH_TRUST_HOST=true
        - NODE_ENV=production
        - NEXTAUTH_SECRET=vrai_secret_tres_securise_ici
        - INTERNAL_API_URL=http://backend:8000/api
        - NEXT_PUBLIC_API_URL=http://localhost:8000/api
      depends_on:
        - backend
      networks:
        - cesizen_net

  glpi_db:
    image: mariadb:10.11
    container_name: cesizen_glpi_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root_secret
      - MYSQL_DATABASE=glpidb
      - MYSQL_USER=glpi_user
      - MYSQL_PASSWORD=glpi_secret
    volumes:
      - glpi_db_data:/var/lib/mysql
    networks:
      - cesizen_net

  glpi:
    image: elestio/glpi:latest
    container_name: cesizen_glpi
    restart: always
    ports:
      - "8080:80"
    environment:
      - TIMEZONE=Europe/Paris
    depends_on:
      - glpi_db
    networks:
      - cesizen_net

networks:
  cesizen_net:
    driver: bridge

volumes:
  db_data:
  mongo_data:
  glpi_db_data:
