name: Deployment Pipeline CESIZen

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Build & Deploy sur Serveur Linux Privé
    runs-on: self-hosted
    
    steps:
      - name: Récupération des sources
        uses: actions/checkout@v4

      - name: Génération d'un fichier .env backend propre
        run: |
          cat << 'EOF' > flow-backend/.env
          APP_NAME=Flow
          APP_ENV=production
          APP_KEY=
          APP_DEBUG=false
          APP_URL=http://localhost:8000

          DB_CONNECTION=pgsql
          DB_HOST=db
          DB_PORT=5432
          DB_DATABASE=flow_db
          DB_USERNAME=flow_user
          DB_PASSWORD=secret_password

          MONGODB_HOST=mongo
          MONGODB_PORT=27017
          MONGODB_DATABASE=flow_db
          MONGODB_URI=mongodb://mongo:27017/flow_db
          EOF

      - name: Déploiement des conteneurs Docker
        run: |
          docker compose down
          docker compose up -d --build --remove-orphans

      - name: Attente du démarrage des bases
        run: sleep 10

      - name: Initialisation Laravel
        run: |
          docker exec cesizen_backend php artisan config:clear
          docker exec cesizen_backend php artisan cache:clear
          docker exec cesizen_backend php artisan key:generate --force
          docker exec cesizen_backend php artisan migrate --force
