name: Deployment Pipeline CESIZen

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Build & Deploy sur Serveur Linux Privé
    runs-on: self-hosted
    
    steps:
      - name: Récupération des sources
        uses: actions/checkout@v4

      - name: Préparation du fichier .env backend
        run: |
          # Écrasement forcé du .env pour nettoyer les résidus des anciens builds
          cp -f flow-backend/.env.example flow-backend/.env
          
          # Remplace toutes les occurrences locales par le nom des conteneurs
          sed -i 's/127.0.0.1/mongo/g' flow-backend/.env
          sed -i 's/localhost/mongo/g' flow-backend/.env
          sed -i 's/DB_HOST=mongo/DB_HOST=db/g' flow-backend/.env

      - name: Déploiement des conteneurs Docker
        run: |
          docker compose down
          docker compose up -d --build --remove-orphans

      - name: Attente du démarrage des bases (PostgreSQL & MongoDB)
        run: sleep 10

      - name: Initialisation Laravel (Clé, Cache & Migrations)
        run: |
          docker exec cesizen_backend php artisan config:clear
          docker exec cesizen_backend php artisan cache:clear
          docker exec cesizen_backend php artisan key:generate --force
          docker exec cesizen_backend php artisan migrate --force
