name: Deployment Pipeline CESIZen

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Build & Deploy sur Serveur Linux Privé
    runs-on: self-hosted
    
    steps:
      - name: Récupération des sources
        uses: actions/checkout@v4

      - name: Déploiement des conteneurs Docker
        run: |
          docker compose down
          docker compose up -d --build --remove-orphans

      - name: Exécution des migrations de base de données
        run: |
          docker exec cesizen_backend php artisan migrate --force
